# Generated by Django 3.2.5 on 2021-07-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationcategory',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='subnavigationcategory',
            old_name='name',
            new_name='sub_category',
        ),
    ]
