# Generated by Django 3.2.5 on 2021-07-19 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210719_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Заголовок категории')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_min', models.CharField(max_length=40, verbose_name='Нороткое название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена комплекса')),
                ('time', models.CharField(max_length=31, verbose_name='Срок исполнения')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный товар')),
                ('description', models.TextField(default='Описание появится позже', verbose_name='Описание')),
                ('small_image', models.ImageField(upload_to='', verbose_name='Изображение для уникальных анализов на главной странице')),
                ('vendor_code', models.CharField(max_length=63, verbose_name='Артикул')),
                ('is_unic', models.BooleanField(default=False, verbose_name='Уникальный анализ')),
            ],
        ),
        migrations.CreateModel(
            name='ComplexType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex_type', models.CharField(max_length=255, verbose_name='Тип комплекса')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=31, verbose_name='Гендер')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Группа исследований')),
                ('slug', models.SlugField(unique=True)),
                ('complex_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.complextype', verbose_name='Основной тип комплексов анализов')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyzeContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок блока')),
                ('text', models.TextField(verbose_name='Текст блока')),
                ('pos', models.IntegerField(verbose_name='Позиция вывода на странице (от 1 до 10)')),
                ('analyze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.analyze', verbose_name='Для анализа:')),
                ('analyze_content_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.analysecontentcategory', verbose_name='Категория блока')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyzeComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_min', models.CharField(max_length=40, verbose_name='Нороткое название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена комплекса')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярный товар')),
                ('description', models.TextField(default='Описание появится позже', verbose_name='Описание')),
                ('big_image', models.ImageField(upload_to='', verbose_name='Изображение для главного слайдера главной странице')),
                ('small_image', models.ImageField(upload_to='', verbose_name='Изображение для слайдера комплексов на главной странице')),
                ('in_top_five_list', models.BooleanField(default=False, verbose_name='Входит в Топ-5 косплексов (добавить на слайдер компексов)')),
                ('on_main_page', models.BooleanField(default=False, verbose_name='Добавить на главный слайдер')),
                ('complex_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.complextype', verbose_name='Тип комплекса')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.gendertype', verbose_name='Зависит от гендера')),
            ],
        ),
        migrations.AddField(
            model_name='analyze',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.analyzecomplex', verbose_name='Тип комплекса'),
        ),
        migrations.AddField(
            model_name='analyze',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.gendertype', verbose_name='Зависит от гендера'),
        ),
        migrations.AddField(
            model_name='analyze',
            name='search_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.searchgroup', verbose_name=''),
        ),
        migrations.AddField(
            model_name='analysecontentcategory',
            name='analyze',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.analyze', verbose_name='Анализ'),
        ),
    ]
