# Generated by Django 3.2.5 on 2021-07-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210719_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyze',
            name='description',
        ),
    ]
