# Generated by Django 3.2.5 on 2021-07-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210720_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzecomplex',
            name='analyzes',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='mainapp.Analyze'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена'),
        ),
    ]
