# Generated by Django 3.2.5 on 2021-07-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_aboutuscategory_aboutuscontentblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyze',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/', verbose_name='Изображение для уникальных анализов на главной странице'),
        ),
        migrations.AlterField(
            model_name='analyzecomplex',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/', verbose_name='Изображение для слайдера комплексов на главной странице'),
        ),
    ]
