# Generated by Django 3.2.5 on 2021-07-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210723_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=127, verbose_name='Краткое описание')),
                ('icon', models.ImageField(upload_to='achievements', verbose_name='Иконка')),
                ('in_archive', models.BooleanField(default=False, verbose_name='В архиве')),
            ],
        ),
        migrations.AlterField(
            model_name='analyze',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='analyzes', verbose_name='Изображение для уникальных анализов на главной странице'),
        ),
        migrations.AlterField(
            model_name='analyzecomplex',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='complexes/main-slider', verbose_name='Изображение для главного слайдера главной странице'),
        ),
        migrations.AlterField(
            model_name='analyzecomplex',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='complexes/complex-slider', verbose_name='Изображение для слайдера комплексов на главной странице'),
        ),
    ]
