# Generated by Django 3.2.5 on 2021-08-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20210724_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyze',
            name='complex',
        ),
        migrations.RemoveField(
            model_name='analyze',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='analyze',
            name='search_group',
        ),
        migrations.RemoveField(
            model_name='analyzecomplex',
            name='complex_type',
        ),
        migrations.RemoveField(
            model_name='analyzecomplex',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='analyzecontentblock',
            name='analyze',
        ),
        migrations.RemoveField(
            model_name='analyzecontentblock',
            name='analyze_content_category',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cartanalyze',
            name='analyze',
        ),
        migrations.RemoveField(
            model_name='cartanalyze',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartanalyze',
            name='user',
        ),
        migrations.RemoveField(
            model_name='navigationcategory',
            name='link',
        ),
        migrations.RemoveField(
            model_name='subnavigationcategory',
            name='link',
        ),
        migrations.DeleteModel(
            name='AnalyseContentCategory',
        ),
        migrations.DeleteModel(
            name='Analyze',
        ),
        migrations.DeleteModel(
            name='AnalyzeComplex',
        ),
        migrations.DeleteModel(
            name='AnalyzeContentBlock',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartAnalyze',
        ),
        migrations.DeleteModel(
            name='GenderType',
        ),
    ]
