# Generated by Django 3.2.5 on 2021-08-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20210825_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyze',
            name='gender',
            field=models.CharField(choices=[('male', 'мужской'), ('female', 'женский'), ('any', 'любой')], default='any', max_length=32, verbose_name='Гендер '),
        ),
        migrations.AlterField(
            model_name='analyzecomplex',
            name='gender',
            field=models.CharField(choices=[('male', 'мужской'), ('female', 'женский'), ('any', 'любой')], default='any', max_length=32, verbose_name='Гендер '),
        ),
        migrations.AlterField(
            model_name='analyzecontentblock',
            name='analyze_content_category',
            field=models.CharField(choices=[('DESCRIPTION', 'Описание'), ('PREPARATIONS', 'Подготовка'), ('INDICATIONS_FOR_USE', 'Показания к применению'), ('FEEDBACK', 'Интерпретация результатов')], default='DESCRIPTION', max_length=32, verbose_name='Категория блока'),
        ),
    ]
