# Generated by Django 3.2.5 on 2021-08-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_remove_cartitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('place', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('place_type', models.CharField(choices=[('OFFICE', 'В офисе'), ('AT_HOME', 'Выезд на дом')], default=None, max_length=8, verbose_name='Тип адреса')),
                ('status', models.CharField(choices=[('IN_PROCESSING', 'В обработке'), ('WAIT_PAYMENT', 'В ожидании оплаты'), ('PAID', 'Оплачен'), ('WAIT_RESULTS', 'В ожидании результатов'), ('COMPLETED', 'Завершен'), ('CANCELED', 'Отменен')], default='IN_PROCESSING', max_length=32, verbose_name='Статус')),
                ('date_done', models.DateTimeField(blank=True, default=None, verbose_name='Даза завершения')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.cart', verbose_name='Товары')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.customer', verbose_name='Покупатель')),
            ],
        ),
    ]
