# Generated by Django 3.2.5 on 2021-09-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20210830_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='father_name',
            field=models.CharField(default=None, max_length=127, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default=None, max_length=127, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='customer',
            name='second_name',
            field=models.CharField(default=None, max_length=127, null=True, verbose_name='Фамилия'),
        ),
    ]
