# Generated by Django 3.2.5 on 2021-09-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20210901_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_full_name',
            field=models.CharField(default=None, max_length=127, null=True, verbose_name='ФИО покупателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, verbose_name='почта для рассылки оповещений'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=None, max_length=127, null=True, verbose_name='Номер телефона'),
        ),
    ]
